apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: dice-roller
    argocd/app-name: demo-argo
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=argocd'
  name: sagar
  title: 'B for Backstage'
  description: An example of a Backstage application.    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental