apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: dice-roller
    backstage.io/kubernetes-namespace: demo
  name: sagar
  title: 'B for Backstage'
  description: An example of a Backstage application.    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental